image: docker:latest

stages:
  - syntax

before_script:
  - source ci/prepare

codesniffer:
  stage: syntax
  image: registry.services.wexo.dk:4567/wexo-services/docker-magento:shopware-plugins-codesniffer-7.4
  script:
    - ~/phpcs.sh
  allow_failure: false
