image: docker:latest

stages:
  - syntax
  - validate-plugin
  - publish-plugin

variables:
  PLUGIN_NAME: WexoQuickpay
  FROSH_UPLOADER_IMAGE: registry.services.wexo.dk:4567/wexo-services/docker-magento/froshplugin-cli:latest
  CODESNIFFER_IMAGE: registry.services.wexo.dk:4567/wexo-services/docker-magento/shopware-plugins-quality-php:8.1-fpm
  SHOPWARE_CLI_ACCOUNT_EMAIL: $SHOPWARE_STORE_USER
  SHOPWARE_CLI_ACCOUNT_PASSWORD: $SHOPWARE_STORE_PASSWORD

before_script:
  - source ci/prepare

codesniffer:
  stage: syntax
  image: $CODESNIFFER_IMAGE
  script:
    - ~/phpcs.sh
  allow_failure: false

validate-plugin:
  stage: validate-plugin
  image:
    name: $FROSH_UPLOADER_IMAGE
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
  script:
    - shopware-cli extension zip . --disable-git
    - shopware-cli extension validate $PLUGIN_NAME.zip

upload-plugin:
  needs: ["validate-plugin"]
  stage: publish-plugin
  only:
    - tags
  except:
    - branches
  when: manual
  image:
    name: $FROSH_UPLOADER_IMAGE
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
  script:
    - shopware-cli extension zip . --disable-git
    - shopware-cli account producer extension upload $PLUGIN_NAME.zip

