monolog:
  channels:
    - quickpay

  handlers:
    quickpay:
      channels: quickpay
      path: "%kernel.logs_dir%/quickpay_%kernel.environment%.log"
      type: rotating_file
      handler: nested
      date_format: Y-m
      max_files: 6
      level: error

    # Omit QuickPay loggin in main log.
    main:
      channels:
        elements: [ "!quickpay" ]

when@dev:
  monolog:
    handlers:
      quickpay:
        type: stream
